# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_auto_20171020_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_pno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s_pno',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(default='+91', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondary_no',
            field=models.CharField(default='+91', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='f_name',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='m_name',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
    ]
