# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='name1',
        ),
        migrations.AddField(
            model_name='portal',
            name='Title',
            field=models.CharField(default='Title', max_length=50),
        ),
        migrations.AddField(
            model_name='portal',
            name='file',
            field=models.FileField(default='FileField', upload_to=''),
        ),
        migrations.AddField(
            model_name='portal',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
