# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171024_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_Manuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Title', max_length=50)),
                ('file', models.FileField(default='FileField', upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Title', max_length=50)),
                ('file', models.FileField(default='FileField', upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Author', models.CharField(default='Anonymous', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sample_Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Title', max_length=50)),
                ('file', models.FileField(default='FileField', upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Title', max_length=50)),
                ('file', models.FileField(default='FileField', upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
