# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_reference_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='Div',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
        migrations.AddField(
            model_name='timetable',
            name='Image',
            field=models.ImageField(default='None', upload_to=None),
        ),
    ]
